### ISSUE TITLE
Flow requirement

### ISSUE THREAD

**Issue by cgestes** [quentinvernot/dumb-reducer#2]
```
./node_modules/dumb-reducer/es/index.js
Module parse failed: Unexpected token (2:7)
You may need an appropriate loader to handle this file type.
| // @flow
| export type SpecialReducer = (state: Object, payload: Object) => Object;
| export type SpecialReducers = { [string]: SpecialReducer };
```

Flow plugins is required to parse the files provided by dumb-reducer.

Is this a wanted behavior?

**Comment by cgestes** [comment]
hence, it doesn't work with an out-of-the-box create-react-app project.

**Comment by quentinvernot** [comment]
Turns out it was a lot easier than I thought, should be all fixed now. The 'es' build strips flow but keeps the rest intact, while flow types are still exported using flow-copy-source.
